directdmgbreaksglass = true
rangedmgbreaksglass = false
environmentaldmgbreaksglass = false
rapiersperformlunges = true
#Range: 5 ~ 15
bloodkillsrequirement = 10
#Range: 1 ~ 3
goldspecialeffectmultiplier = 1
#Range: 1 ~ 3
bloodspecialeffectmultiplier = 1
rangedmgresetsrhythmlevel = false
environmentaldmgresetsrhythmlevel = false
#Range: 300 ~ 1200
mintimenotmovingtoresetrhythmlevel = 600
crossbowsdopiercingdamage = true
thrownweaponsdopiercingdamage = true
daggeroffrostmelts = false
shrineofpeaceremovesarmor = true
shrineofpeacegiveslessabsorption = true

