
[instrumentus]
	#Sickles mass harvest leaf and tall-grass blocks, their range increases the higher the tool level
	enable_sickles = true
	#Hammers mine in a 3x3 Radius, made of every single tool material.
	enable_hammers = true
	#Utility items currently present in instrumentus is the Soul-Infused Pickaxe, which places light blocks on right click
	enable_util = true
	#Material variants for iron shears (Wood-Netherite)
	enable_shears = true
	#RF-Powered tools made of diamonds, emeralds and redstone. This will also disable carbon rods.
	enable_energized = true
	#Armor with special set-bonus abilities
	enable_armor = true
	#Knives harvest plant fiber from tall grass, which can be used to make string. Disables Knives as well as plant fiber.
	enable_knives = true
	#The original item in the mod! Paxels are a tool able to mine all blocks that an Axe, Pickaxe and Shovel Can
	enable_paxels = true

