
["EFFECT CHANCE"]
	#Chance to proc Storm on hit
	"Storm Chance" = 15
	#Chance to proc Wildfire on hit
	"Wildfire Chance" = 10
	#Chance to proc Omen (Instant-kill) on hit
	"Omen Chance" = 10
	#Chance to proc Watcher (lifesteal) on hit
	"Watcher Chance" = 15
	#Chance to proc Speed on hit
	"Speed Chance" = 15
	#Chance to proc Levitate on hit
	"Levitate Chance" = 15
	#Chance to proc Plague on hit
	"Plague Chance" = 15
	#Chance to spread Plague
	"Plague Spread Chance" = 15
	#Chance to proc Bramble on hit
	"Bramble Chance" = 15
	#Chance to proc Brimstone on hit
	"Brimstone Chance" = 15
	#Chance to proc Slowness on hit
	"Slowness Chance" = 50
	#Chance to proc Freeze on hit
	"Freeze Chance" = 15
	#Chance to proc Poison on hit
	"Poison Chance" = 15

["EFFECT DURATION"]
	#Duration of Wildfire
	"Wildfire Duration" = 8
	#Duration of Speed
	"Speed Duration" = 300
	#Duration of Levitate
	"Levitate Duration" = 50
	#Duration of Plague
	"Plague Duration" = 180
	#Duration of Bramble
	"Bramble Duration" = 180
	#Duration of Slowness
	"Slowness Duration" = 50
	#Duration of Freeze
	"Freeze Duration" = 120
	#Duration of Poison
	"Poison Duration" = 180

[MISC]
	#When target HP is below this flat value Omen can proc
	"Omen Threshold" = 60.0
	#Absorption granted on Omen proc
	"Omen Absorption" = 0.5
	#Health gained per target effected by Watcher proc
	"Watcher Heal" = 0.5
	#The chance of SimplySwords loot spawning in chests (1 = 100%)
	"Loot Weight" = 0.1

