
#Items
[items]
	#The default payment item. Format is "namespace:item"
	payment_item = "vendingmachine:money"
	#Set to 0 if you don't want to give new players money, else set to the amount of money to give new players.
	#Range: 0.0 ~ 1.7976931348623157E308
	start_money = 1000.0
	#Item prices. Format is "namespace:item price"
	item_prices = ["minecraft:dirt 1"]
	#Set to true if players can edit item prices per-machine.
	allow_editing = true
	#Set to true if prices are per-stack and not per-item
	is_stack_price = false
	#Maximum value of a stack inside a Vending Machine
	#Range: 1 ~ 1024
	max_stack = 1024

